a = input('Digite algo: ')
#print('O tipo primitivo desse valor é ', type(a))
#print('Só tem espaços? ', a.isspace())
#print('É um número? ', a.isnumeric())
#print('É alfabético? ', a.isalpha())
#print('É alfanumerico? ', a.isalnum())
#print('Está em maiusculas? ', a.isupper())
#print('Está em minusculas? ', a.islower())
#print('Está capitalizada? ', a.istitle())

print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaço? {}'.format(a.isspace()))
print('É um números? {}'.format(a.isnumeric()))
print('É alfabetico? {}'.format(a.isalpha()))
print('É alfanumerico? {}'.format(a.isalnum()))
print('Esta em maiusculas? {}'.format(a.isupper()))
print('Esta em minusculas? {}'.format(a.islower()))
print('Esta capitalizada? {}'.format(a.istitle()))